# Database
spring.datasource.url=jdbc:mysql://localhost:3306/se330?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=8080

#firebase
firebase.credentials.path=src/main/resources/se330-6d2ee-firebase-adminsdk-fbsvc-08913dc476.json